version: '3'
services:
        base:
                build: ./base
                image: centos_moose_base:latest
                volumes: 
                  - ./moose_pkg_install:/opt/moose
        libmesh:
                build: ./libmesh
                image: centos_moose_libmesh:latest
                volumes:
                 - ./moose_pkg_install:/opt/moose
                 - fs_projects:/projects
        framework_test:
                build: ./framework_test
                image: centos_moose_framework_test:latest
                volumes:
                 - ./moose_pkg_install:/opt/moose
                 - fs_projects:/projects
                   
volumes:
        fs_projects:

